services:
    traffic-lab-mysql-db:
        image: mysql:5.7
        restart: always
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: traffic-lab-db
            MYSQL_USER: traffic-lab
            MYSQL_PASSWORD: password
        ports:
            - 3316:3306
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        volumes:
            - /Users/kimnelson/mysql-local-storage/5.7/db:/var/lib/mysql